[package]
name = "hanabi_property_size_bug"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.1"
bevy_hanabi = { git = "https://github.com/djeedai/bevy_hanabi.git" }
# bevy_hanabi = "0.10.0"
